version: '3'
services:
  php:
    build: build/php
    expose:
      - '9000'
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log
  web:
    build: build/nginx
    restart: always
    ports:
        - '81:80'
    depends_on:
        - php
        - mysql
    links:
        - mysql
    volumes:
        - ./:/var/www/html
        - ./logs:/var/log/nginx
  mysql:
      image: mysql:5.7
      ports:
        - 13306:3306
      environment:
        MYSQL_DATABASE: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: password
